"""empty message

Revision ID: 5158edd5a8d9
Revises:
Create Date: 2025-10-25 21:06:39.898941

"""  # noqa: D400, D415, INP001

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5158edd5a8d9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("second_name", sa.String(length=64), nullable=True),
        sa.Column("gender", sa.String(length=1), nullable=True),
        sa.Column("company", sa.String(length=128), nullable=True),
        sa.Column("join_date", sa.Date(), nullable=True),
        sa.Column("job_title", sa.String(length=128), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("guid", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("guid", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "project",
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tech_stack", postgresql.ARRAY(sa.String(), as_tuple=True), nullable=False),
        sa.Column("additional_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("constraint_date", sa.Date(), nullable=False),
        sa.Column("creator_guid", sa.Uuid(), nullable=False),
        sa.Column("mentor_guid", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("guid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["creator_guid"], ["user.guid"], name=op.f("fk_project_creator_guid_user")),
        sa.ForeignKeyConstraint(["mentor_guid"], ["user.guid"], name=op.f("fk_project_mentor_guid_user")),
        sa.PrimaryKeyConstraint("guid", name=op.f("pk_project")),
    )
    op.create_table(
        "task",
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("project_guid", sa.Uuid(), nullable=False),
        sa.Column("executor_guid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("guid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["executor_guid"], ["user.guid"], name=op.f("fk_task_executor_guid_user")),
        sa.ForeignKeyConstraint(["project_guid"], ["project.guid"], name=op.f("fk_task_project_guid_project")),
        sa.PrimaryKeyConstraint("guid", name=op.f("pk_task")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    op.drop_table("project")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
